name: pkg-update

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - actions/trigger/pkg-update

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-arch: [x86]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.3.1

      - uses: actions/checkout@v2
      - name: Update Manifest.toml
        run: julia --project=. -e "import Pkg; Pkg.update()"

      # https://github.com/marketplace/actions/create-pull-request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update */Manifest.toml
          title: '[AUTO] Update */Manifest.toml'
          labels: no changelog
          branch: create-pull-request/pkg-update
          branch-suffix: none
          base: master
      - name: Check output environment variable
        run: echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
